language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"

# install Java8 as required by vnu.jar
before_install:
 - sudo apt-get update
 - sudo apt-get install oracle-java8-installer
 - sudo update-java-alternatives -s java-8-oracle

install:
 - "pip install ."
script: "python setup.py test"
